### ISSUE TITLE
There are a lot of bugs in the code

### ISSUE THREAD

**Issue by shiningspark** [Rohit-Kundu/Two-Step-Feature-Enhancement#1]
I hope the author can improve it and specify the data set format of the code. Thanks @Rohit-Kundu

**Comment by MajidHeydari** [comment]
No data available Is it possible to add data?

**Comment by Rohit-Kundu** [comment]
All are open-access datasets and have been cited in the paper.

1. Herlev Pap Smear dataset by Jantzen et al.:http://mde-lab.aegean.gr/index.php/downloads  
2. Mendeley Liquid Based Cytology dataset by Hussain
et al.: https://data.mendeley.com/datasets/zddtpgzv63/4    
3. SIPaKMeD Pap Smear dataset by Plissiti et al.: https://www.cs.uoi.gr/~marina/sipakmed.html
