### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by MajidHeydari** [Rohit-Kundu/Two-Step-Feature-Enhancement#2]
The project has an error and is not executable
parser.add_argument('--num_csv', type=int, required = True, help='How many csv files of features do you have?')

**Comment by MajidHeydari** [comment]
resnet50.csv file does not exist

**Comment by hritam-98** [comment]
Dear Majid. We did not provide the CSV. If you want to run the code, please generate the CSV first. We have provided details in the paper and we believe this is enough for reproducibility. Having said this, I think we can close this issue
